### ISSUE TITLE
setup.py 

### ISSUE THREAD

**Issue by necrose99** [Techcrafter/Plymouth-Creator#2]
[requirements.txt](https://github.com/Techcrafter/Plymouth-Creator/files/5048351/requirements.txt)
[setup.py,txt](https://github.com/Techcrafter/Plymouth-Creator/files/5048352/setup.py.txt)
 
pip freeze > requirements.txt

https://pypi.org/project/setuppy-generator/

makes it far simpler to package for other linux distros.. and or etc.. 

pyinstalller / freeze to exe etc..

**Comment by Techcrafter** [comment]
I don't see any good reason to use this.
The run script does the work as well!

**Comment by necrose99** [comment]
_sudo apt install python2 python-tk ffmpeg_ 

not everyone is using Debian derived distros. ...

http://gpo.zugaina.org/dev-python/pydns , 
gentoos means of pthon packaging ,   easy as pie to sawp over to this python , cavets ... neets setup.py to work ..

{ https://github.com/fedora-python/pyp2rpm , amounst other distros. arch etc , setup.py makes packaging for more and or devs more likely to contribute. 
https://pypi.org/project/stdeb/  automatic deb out ,  dh-python newer-ish @debian }

dev-lang/python-exec , (wrapps python pkgs ie scripts to executables , and or with eselect can pick what  underlying python 3.x 3.10 beta , .6 .7 etc. [symbolic links)  do to this pip install other than $USER will goat screw  any gentoo/funtoo or gentoo alike system.   
dev-lang/python [tk]  force tk into python language build. 
dev-python/pygobject or simular for gtk3 deps 

[Plymouth-Creator.zip](https://github.com/Techcrafter/Plymouth-Creator/files/6085528/Plymouth-Creator.zip)

**bit test-ish so dev branch** ,  my dyslexic hide isnt the greatest week-end-warrior coder by far , however 
having this run on my @pentoo box to hack out a Plymouth theme for Pentoo (Gentoo) might be of use.. 

feel free to test the copy of this .

**Comment by Techcrafter** [comment]
If you want to submit any improvements for this application, please create a pull request.
If everything looks good, I'll merge it into the repository!

**Comment by necrose99** [comment]
Will do just got laptop from repair shop.. dc jack had to be reballed. , replaced..  ill make a pull to dev/dev branch
